### ISSUE TITLE
Weird caching issues on address pages

### ISSUE THREAD

**Issue by diwakergupta** [blockstack/blockstack-explorer#171] opened 2019-10-31 14:21 UTC
There are a number of oddities when trying to load up an address page, e.g. https://explorer.blockstack.org/address/stacks/SP1P72Z3704VMT3DMHPP2CB8TGQWGDBHD3RPR9GZS

* Directly hitting that URL generally results in an empty page.
* Searching for the address in the search bar sometimes results in a 404 from the explorer-api backend (see [screenshot](https://www.dropbox.com/s/sng8ohu9nrcgk9b/Screenshot%202019-10-31%2010.15.47.png?dl=0))
* Re-doing the search directly sometimes works. But then, if you simply refresh the page (equivalent to directly hitting the URL), the page renders empty again

All the data seems correctly reflected in the backend database, so this feels very much like client-side caching issues or other bugs in the explorer app.

I believe @wileyj also reproduced all the above after clearing the explorer cache.

**Comment by wileyj** [comment] 2019-10-31 14:52
to add some more details: all data in the DB's appear to be accurate, I'm able to query transactions listed at that address. 
i also cleared the redis cache, at which point i was able to navigate to the address page by searching...but as diwaker noted, refreshing the page after it loads returns the 404. 

interestingly, on refresh there is nothing in the logs whatsoever. only on a fresh page load. 

one thing to note is that the page size for this address is a little large, roughly 300k, page load time when it does work can take up to 30s.

**Comment by diwakergupta** [comment] 2019-10-31 14:57
Yeah, we should look into paginating transactions or loading them on demand for these kind of pages.

**Comment by hstove** [comment] 2019-10-31 16:04
Yep, I think this is due to pagination and a timeout issue. On it

**Comment by diwakergupta** [comment] 2019-10-31 19:31
@wileyj can you open a separate devops issue to add some monitoring around this? Now that @hstove has a fix, it should be easier to add alerting to the exact backend issue (e.g. timeouts or 404s etc) Thanks.

**Comment by hstove** [comment] 2019-11-06 21:00
@timstackblock I'm moving this to QA. This bug was caused by too much data being sent/cached on the backend, causing timeouts and other issues. Truncating the TX list to 50 entries at most has stabilized this issue.

**Comment by timstackblock** [comment] 2019-11-08 14:07
Part of the issue was fixed with truncating the TX list to 50 but we I am still seeing something strange when I refresh the page.

The latest transaction for 945 STX disappears when the page is refreshed

Please see the video below
https://screencast-o-matic.com/watch/cqXj2nUQYy

Searching the address in the search box gives me the latest transactions

<img width="1417" alt="Screen Shot 2019-11-08 at 9 05 10 AM" src="https://user-images.githubusercontent.com/49165468/68482183-f8799b80-0206-11ea-863c-4c9f294ec471.png">

But Refreshing the page causes the latest transactions to disappear from the top of the page

<img width="1416" alt="Screen Shot 2019-11-08 at 9 04 55 AM" src="https://user-images.githubusercontent.com/49165468/68482216-09c2a800-0207-11ea-8889-dceee6c0c415.png">

**Closed** 2019-11-13 18:38 UTC
Labels: P1 bug
