### ISSUE TITLE
Explorer is not showing usernames newer than 3 days ago/not returning search results

### ISSUE THREAD

**Issue by ryanarndtcm** [blockstack/blockstack-explorer#194] opened 2019-12-16 15:31 UTC
showing the same way across chrome, firefox, safari

![image](https://user-images.githubusercontent.com/52256509/70919663-a131cc80-1ff7-11ea-9592-a6708189ac68.png)

**Comment by diwakergupta** [comment] 2019-12-16 18:14
@wileyj found the issue and deployed a fix in production. We're still diagnosing the root cause internally, closing this out for now.

**Closed by diwakergupta** 2019-12-16 18:14 UTC
